### ISSUE TITLE
Can we add image to the person boxes?

### ISSUE THREAD

**Issue by montesajudy** [djfun/geneajs#1]

**Comment by siddhesh-vartak98** [comment]
Yes you can add images in node. For that you have to add line in "draw: function (inData, inLines, inTemplate)" function as following code - 

<code>
data.forEach(function (dat, dat_ind, data){
var image = "your image path";

returnData += "<div class='data_node gender_" + gender + "' style='top:" + dat.top + "px; " +
    "left:" + dat.left + "px; height:" + ChartHelper.height + "px; " +
    "width:" + ChartHelper.width + "px;' data-dataObj='" + nodeID + "'>" +
    "<div class='text-center'><img src='" + image + "' alt='profile_img' class='profile_img' ></div> " +
    "<div align='center' class='textClass'>" +
    handlebarsTemplate(dat.data) +
        "</div>" + 
    "</div>";
}
</code>
The class='textClass' is custom class.

**Comment by siddhesh-vartak98** [comment]
Yes you can add images in node. For that you have to add line in "draw: function (inData, inLines, inTemplate)" function as following code 

data.forEach(function (dat, dat_ind, data){
var image = "your image path";

returnData += "<div class='data_node gender_" + gender + "' style='top:" + dat.top + "px; " +
    "left:" + dat.left + "px; height:" + ChartHelper.height + "px; " +
    "width:" + ChartHelper.width + "px;' data-dataObj='" + nodeID + "'>" +
    "<div class='text-center'><img src='" + image + "' alt='profile_img' class='profile_img' ></div> " +
    "<div align='center' class='textClass'>" +
    handlebarsTemplate(dat.data) +
        "</div>" + 
    "</div>";
}


The class='textClass' is custom class.

**Comment by siddhesh-vartak98** [comment]
Yes you can add images in node. For that you have to add line in "draw: function (inData, inLines, inTemplate)" function as following code 

data.forEach(function (dat, dat_ind, data){
var image = "your image path";

and in returnData add a line <img src= 'image' alt='profile_img' class='profile_img'>

The class='textClass' is custom class.

**Comment by siddhesh-vartak98** [comment]
Yes you can add images in node. For that you have to add line in "draw: function (inData, inLines, inTemplate)" function as following code 

data.forEach(function (dat, dat_ind, data) function add 

var image = "your image path";

and in returnData add a image tag
